### ISSUE TITLE
Problems about the usage of scenarios from maddpg

### ISSUE THREAD

**Issue by ryrobotics** [LXYYY/marl_formation#1]
Thanks for your great job! It is very helful and meaningful.

When I try to run `python experiments/env_test.py --scenario=simple_tag.py` I will get the error below
`Traceback (most recent call last):
  File "experiments/env_test.py", line 26, in <module>
    env.render()
  File "/home/marl_formation/multirobot/environment/environment.py", line 87, in render
    for vehicle in self.world.vehicles:
AttributeError: 'World' object has no attribute 'vehicles'`
I am confused of the relevant content in readme, so do you have any solutions to this problem? Thank you very much.

**Comment by mikexyl** [comment]
hi, it's just a small project between us three, it's really rough now. I will have a look at into your issue. But with a first a glance, it's a import issue. I wrote a few objects that's inhereted from multiagent.World, and all named World. This error should be caused by importing a wrong World. But I remember I didn't run into this issue before I commit.

**Comment by mikexyl** [comment]
env_test.py requires the world object you import must have veichles member. It's a missing feature. You can add a checking to  env_test.py that if no veichle,don't display veichles. Or wait me to update. (And you shouldn't expect further updates, since we are barelly doing this project.

**Comment by ryrobotics** [comment]
Thanks for your assistance! Anyway, the code inspires me and I will try to fix the problem.
